# install: conda env create -f DEEPLABCUT.yaml
# update:  conda env update -f DEEPLABCUT.yaml
name: 
channels:
  - conda-forge
dependencies:
  - opencv
  - tqdm
  - numpy
  - ffmpeg
  - pip:
    - ffmpeg-python