# install: conda env create -f requirements.yaml
# update:  conda env update -f requirements.yaml
name: bio-proj
channels:
  - conda-forge
dependencies:
  - python=3.10
  - opencv
  - tqdm
  - numpy
  - ipywidgets