# install: conda env create -f requirements.yaml
# update:  conda env update -f requirements.yaml
name: bio_proj
channels:
  - conda-forge
dependencies:
  - ultralytics
  - opencv
  - tqdm
  - numpy
  - ipywidgets